In [9]:
import pandas as pd
import random as ra
import numpy as np
import warnings

warnings.filterwarnings('ignore')

## Задание 1

Создадим вспомогательные функции для разделения списка республик случайным образом на 3 части и для сложения 2-мерного массива в одномерный (np.flatten() не подходит)

In [43]:
republics = ['РСФСР', 'Украинская ССР', 'Белорусская ССР', 'Узбекская ССР',
          'Казахская ССР', 'Грузинская ССР', 'Азербайджанская ССР',
          'Литовская ССР', 'Молдавская ССР', 'Латвийская ССР', 'Киргизская ССР',
          'Таджикская ССР', 'Армянская ССР', 'Туркменская ССР', 'Эстонская ССР']

departs = ['Сельское хозяйство', 'Легкая промышленность', 'Тяжелая промышленность группы А',
           'Тяжелая промышленность группы Б', 'Военно промышленный комплекс',
           'Наука', 'Химическая промышленность']

def get_random_departs(departs):
    deps = departs.copy()
    r_deps = []
    for i in range(3):
        ra.shuffle(deps)
        
        size = ra.randint(1, len(deps) - 2 + i)
        sampl = deps[:size]
        
        if i == 2:
            sampl = deps
        
        r_deps.append(sampl)
        
        deps = deps[size:]
        
    return r_deps


def l_flatten(lst):
    temp_list = []
    for el in lst:
        try:
            temp_list.extend(el)
        except TypeError:
            temp_list.append(el)
    return temp_list

Создадим датафрейм с характеристиками для каждой республики и заполним его случайным образом отраслями, а также подсчитаем индексы развития республик в целом

In [44]:
repubs = sorted(ra.sample(republics, ra.randint(3, 15)))
length = len(repubs)
data = [(repub, '', '', '', 0, 0) for repub in repubs]
data = pd.DataFrame(data, columns=['Название республики', 'Избыточно развитые', 'Сбалансированно развитые', 'Слабо развитые',
                             'Индекс избыточно развитых', 'Индекс слабо развитых'])
data

,Название республики,Избыточно развитые,Сбалансированно развитые,Слабо развитые,Индекс избыточно развитых,Индекс слабо развитых
0,Азербайджанская ССР,,,,0,0
1,Армянская ССР,,,,0,0
2,Белорусская ССР,,,,0,0
3,Казахская ССР,,,,0,0
4,Киргизская ССР,,,,0,0
5,Латвийская ССР,,,,0,0
6,Литовская ССР,,,,0,0
7,Молдавская ССР,,,,0,0
8,РСФСР,,,,0,0
9,Таджикская ССР,,,,0,0
10,Туркменская ССР,,,,0,0
11,Узбекская ССР,,,,0,0
12,Украинская ССР,,,,0,0
13,Эстонская ССР,,,,0,0

In [45]:
keys = ['Избыточно развитые', 'Сбалансированно развитые', 'Слабо развитые']
for i in range(len(data)):
    deps = get_random_departs(departs)
    for j in range(3):
        data.at[i, keys[j]] = deps[j]
        if j == 0:
            data.at[i, 'Индекс избыточно развитых'] = len(deps[j])
        elif j == 2:
            data.at[i, 'Индекс слабо развитых'] = -len(deps[j])
data

,Название республики,Избыточно развитые,Сбалансированно развитые,Слабо развитые,Индекс избыточно развитых,Индекс слабо развитых
0,Азербайджанская ССР,[Военно промышленный комплекс],"[Наука, Тяжелая промышленность группы Б, Сельс...","[Химическая промышленность, Легкая промышленно...",1,-3
1,Армянская ССР,"[Тяжелая промышленность группы А, Сельское хоз...",[Тяжелая промышленность группы Б],"[Военно промышленный комплекс, Наука, Химическ...",2,-4
2,Белорусская ССР,"[Сельское хозяйство, Военно промышленный компл...","[Тяжелая промышленность группы А, Наука]",[Легкая промышленность],4,-1
3,Казахская ССР,"[Военно промышленный комплекс, Тяжелая промышл...",[Легкая промышленность],[Химическая промышленность],5,-1
4,Киргизская ССР,"[Военно промышленный комплекс, Легкая промышле...","[Тяжелая промышленность группы Б, Химическая п...","[Тяжелая промышленность группы А, Наука]",3,-2
5,Латвийская ССР,"[Химическая промышленность, Наука]",[Военно промышленный комплекс],"[Сельское хозяйство, Легкая промышленность, Тя...",2,-4
6,Литовская ССР,"[Легкая промышленность, Химическая промышленно...",[Сельское хозяйство],"[Военно промышленный комплекс, Наука, Тяжелая ...",3,-3
7,Молдавская ССР,"[Тяжелая промышленность группы А, Военно промы...","[Легкая промышленность, Сельское хозяйство, Хи...","[Наука, Тяжелая промышленность группы Б]",2,-2
8,РСФСР,"[Химическая промышленность, Тяжелая промышленн...","[Тяжелая промышленность группы Б, Военно промы...","[Наука, Легкая промышленность]",3,-2
9,Таджикская ССР,"[Военно промышленный комплекс, Тяжелая промышл...","[Сельское хозяйство, Наука]",[Легкая промышленность],4,-1
10,Туркменская ССР,"[Военно промышленный комплекс, Сельское хозяйс...","[Наука, Легкая промышленность]","[Тяжелая промышленность группы Б, Тяжелая пром...",2,-3
11,Узбекская ССР,"[Сельское хозяйство, Легкая промышленность]","[Военно промышленный комплекс, Тяжелая промышл...",[Химическая промышленность],2,-1
12,Украинская ССР,"[Химическая промышленность, Сельское хозяйство...","[Тяжелая промышленность группы А, Военно промы...","[Тяжелая промышленность группы Б, Легкая промы...",3,-2
13,Эстонская ССР,"[Тяжелая промышленность группы Б, Сельское хоз...",[Химическая промышленность],"[Наука, Тяжелая промышленность группы А, Легка...",2,-4

In [46]:
deps = [(dep, 0, 0, 0, 0) for dep in departs]
deps = pd.DataFrame(deps, columns=['Отрасль', 'Избыточно развитые', 'Сбалансированно развитые',
                                   'Слабо развитые', 'Общий индекс развития'])
deps

,Отрасль,Избыточно развитые,Сбалансированно развитые,Слабо развитые,Общий индекс развития
0,Сельское хозяйство,0,0,0,0
1,Легкая промышленность,0,0,0,0
2,Тяжелая промышленность группы А,0,0,0,0
3,Тяжелая промышленность группы Б,0,0,0,0
4,Военно промышленный комплекс,0,0,0,0
5,Наука,0,0,0,0
6,Химическая промышленность,0,0,0,0

Подсчитаем количество отраслей в каждой категории и заполним таблицу с данными отраслей в соответствие с массивами из первой таблицы

In [47]:
for key in keys:
    dep = l_flatten(data[key])
    for i in range(len(deps)):
        deps.at[i, key] = dep.count(deps.at[i, 'Отрасль'])
        
for i in range(len(deps)):
    dep = deps.iloc[i]
    deps.at[i, 'Общий индекс развития'] = dep['Избыточно развитые'] - dep['Слабо развитые']
deps

,Отрасль,Избыточно развитые,Сбалансированно развитые,Слабо развитые,Общий индекс развития
0,Сельское хозяйство,9,4,1,8
1,Легкая промышленность,3,3,8,-5
2,Тяжелая промышленность группы А,5,3,6,-1
3,Тяжелая промышленность группы Б,5,5,4,1
4,Военно промышленный комплекс,7,4,3,4
5,Наука,3,5,6,-3
6,Химическая промышленность,6,3,5,1

Создадим специальный фрейм для сбора статистики о пиковых отраслях.<br>Индекс развития сбалансированной отрасли не связан с индексами для развитой и отстающей отраслей, потому что индекс сбалансированности не помножен на свой коэффициент (0) для сохранения значения.<br>В некоторых полях отраслей может быть несколько из-за схожести показателей.

In [48]:
stats = pd.DataFrame(columns=['Название отрасли', 'Индекс развития'])
desces = ['Самая развитая отрасль', 'Самая сбалансированная отрасль', 'Самая отстающая отрасль']
for key, desc in zip(keys, desces):
    dep = deps[deps[key] == deps[key].max()].to_dict('list')
    if key == 'Слабо развитые':
        indexes = -dep[key][0]
    else:
        indexes = dep[key][0]
    stats.loc[desc] = ', '.join(dep['Отрасль']), indexes
stats

,Название отрасли,Индекс развития
Самая развитая отрасль,Сельское хозяйство,9
Самая сбалансированная отрасль,"Тяжелая промышленность группы Б, Наука",5
Самая отстающая отрасль,Легкая промышленность,-8

Статистика отраслей по показателям развития со всех стран

In [49]:
deps[['Отрасль', 'Общий индекс развития']].sort_values('Общий индекс развития', ascending=False)

                           Отрасль  Общий индекс развития
0               Сельское хозяйство                      8
4     Военно промышленный комплекс                      4
3  Тяжелая промышленность группы Б                      1
6        Химическая промышленность                      1
2  Тяжелая промышленность группы А                     -1
5                            Наука                     -3
1            Легкая промышленность                     -5